import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Chatbot from './components/Chatbot';
import { Toaster } from 'sonner';
import { CartProvider } from './context/CartContext';
import { OrdersProvider } from "./context/OrdersContext";
import { WishlistProvider } from "./context/wishlist";
import Header from "./components/header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
      <WishlistProvider>

        <CartProvider>
           <OrdersProvider>
          {children}
            <Chatbot />
            <Toaster
  position="top-right"
  expand={true}
  richColors
  closeButton
  duration={5000}
  theme="light" // or "dark", "system"
  visibleToasts={5}
  offset={16}
  gap={12}
  pauseWhenPageIsHidden={true}
  toastOptions={{
    style: {
      background: '#fff',
      color: '#000',
      border: '1px solid #e5e7eb',
      borderRadius: '8px',
      fontSize: '14px',
      fontWeight: '500',
    },
    className: 'custom-toast',
  }}
  />
  </OrdersProvider>
    </CartProvider>
    </WishlistProvider>

        </AuthProvider>
      </body>
    </html>
  );
}
